name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plus-ms-report
    steps:
      - uses: actions/checkout@v3
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version-file: plus-ms-report/.nvmrc
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Unit Tests
        run: npm test
      - name: Test Coverage
        run: npm run coverage
